
import type { Product } from './types';

const getImg = (id: number) => `https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F${id}%2F${id}_1.png`;

export const allProducts: Product[] = [
    // --- LÍNEA ONCOLOUR (MAQUILLAJE) - 24+ PRODUCTOS ---
    { id: 38742, name: "Barra de Labios OnColour - Nude Beige", brand: "OnColour", price: 7.00, imageUrl: getImg(38742), description: "Color vibrante y textura cremosa.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38743, name: "Barra de Labios OnColour - Peach Pink", brand: "OnColour", price: 7.00, imageUrl: getImg(38743), description: "Tono melocotón suave.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38745, name: "Barra de Labios OnColour - Cinnamon Vibe", brand: "OnColour", price: 7.00, imageUrl: getImg(38745), description: "Tono canela cálido.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38749, name: "Barra de Labios OnColour - Prune Red", brand: "OnColour", price: 7.00, imageUrl: getImg(38749), description: "Rojo ciruela intenso.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38751, name: "Barra de Labios OnColour - Red Velvet", brand: "OnColour", price: 7.00, imageUrl: getImg(38751), description: "Rojo clásico aterciopelado.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38753, name: "Barra de Labios OnColour - Coral Red", brand: "OnColour", price: 7.00, imageUrl: getImg(38753), description: "Coral vibrante.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38755, name: "Barra de Labios OnColour - Apricot Coral", brand: "OnColour", price: 7.00, imageUrl: getImg(38755), description: "Albaricoque suave.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 38759, name: "Barra de Labios OnColour - Punch Pink", brand: "OnColour", price: 7.00, imageUrl: getImg(38759), description: "Rosa ponche energético.", stock: 50, category: 'makeup', subCategory: 'OnColour' },
    { id: 36087, name: "Esmalte de Uñas OnColour - Candy Pink", brand: "OnColour", price: 5.00, imageUrl: getImg(36087), description: "Rosa dulce radiante.", stock: 100, category: 'makeup', subCategory: 'OnColour' },
    { id: 36088, name: "Esmalte de Uñas OnColour - Bright Red", brand: "OnColour", price: 5.00, imageUrl: getImg(36088), description: "Rojo pasión clásico.", stock: 100, category: 'makeup', subCategory: 'OnColour' },
    { id: 36089, name: "Esmalte de Uñas OnColour - Deep Red", brand: "OnColour", price: 5.00, imageUrl: getImg(36089), description: "Rojo profundo elegante.", stock: 100, category: 'makeup', subCategory: 'OnColour' },
    { id: 36090, name: "Esmalte de Uñas OnColour - Lavender", brand: "OnColour", price: 5.00, imageUrl: getImg(36090), description: "Tono lila suave.", stock: 100, category: 'makeup', subCategory: 'OnColour' },
    { id: 36091, name: "Esmalte de Uñas OnColour - Purple Gum", brand: "OnColour", price: 5.00, imageUrl: getImg(36091), description: "Morado divertido.", stock: 100, category: 'makeup', subCategory: 'OnColour' },
    { id: 39292, name: "Base de Maquillaje OnColour Power Up - Beige", brand: "OnColour", price: 11.00, imageUrl: getImg(39292), description: "Base ligera para unificar el tono.", stock: 75, category: 'makeup', subCategory: 'OnColour' },
    { id: 38805, name: "Polvos Compactos OnColour - Light", brand: "OnColour", price: 10.00, imageUrl: getImg(38805), description: "Matifica tu piel al instante.", stock: 60, category: 'makeup', subCategory: 'OnColour' },
    { id: 38920, name: "Sombra Mono OnColour - Silver Grey", brand: "OnColour", price: 5.00, imageUrl: getImg(38920), description: "Gris plata con brillo.", stock: 40, category: 'makeup', subCategory: 'OnColour' },
    { id: 38921, name: "Sombra Mono OnColour - Dazzle Beige", brand: "OnColour", price: 5.00, imageUrl: getImg(38921), description: "Beige iluminador.", stock: 40, category: 'makeup', subCategory: 'OnColour' },
    { id: 38922, name: "Sombra Mono OnColour - Sparkle Pink", brand: "OnColour", price: 5.00, imageUrl: getImg(38922), description: "Rosa brillante.", stock: 40, category: 'makeup', subCategory: 'OnColour' },
    { id: 38923, name: "Sombra Mono OnColour - Velvet Plum", brand: "OnColour", price: 5.00, imageUrl: getImg(38923), description: "Ciruela terciopelo.", stock: 40, category: 'makeup', subCategory: 'OnColour' },
    { id: 38929, name: "Máscara de Pestañas OnColour Big Lash - Black", brand: "OnColour", price: 8.00, imageUrl: getImg(38929), description: "Volumen extremo en color negro.", stock: 120, category: 'makeup', subCategory: 'OnColour' },
    { id: 38784, name: "Bálsamo Labial OnColour - Rose", brand: "OnColour", price: 4.50, imageUrl: getImg(38784), description: "Hidratación con un toque de rosa.", stock: 120, category: 'makeup', subCategory: 'OnColour' },
    { id: 40967, name: "Corrector en Stick OnColour - Light", brand: "OnColour", price: 6.00, imageUrl: getImg(40967), description: "Cubre imperfecciones fácilmente.", stock: 90, category: 'makeup', subCategory: 'OnColour' },
    { id: 40968, name: "Corrector en Stick OnColour - Medium", brand: "OnColour", price: 6.00, imageUrl: getImg(40968), description: "Tono medio para imperfecciones.", stock: 90, category: 'makeup', subCategory: 'OnColour' },
    { id: 39338, name: "Delineador de Ojos OnColour - Black", brand: "OnColour", price: 6.00, imageUrl: getImg(39338), description: "Trazo preciso y pigmentado.", stock: 150, category: 'makeup', subCategory: 'OnColour' },

    // --- CUIDADO FACIAL (SKINCARE) - 25+ PRODUCTOS ---
    { id: 41030, name: "Limpiador en Gel Novage+ Refresh", brand: "Novage+", price: 32.00, imageUrl: getImg(41030), description: "Limpieza bio-nutritiva profunda.", stock: 50, category: 'skincare', subCategory: 'Novage+' },
    { id: 41031, name: "Contorno de Ojos Novage+ Lift + Firm", brand: "Novage+", price: 38.00, imageUrl: getImg(41031), description: "Efecto tensor inmediato.", stock: 40, category: 'skincare', subCategory: 'Novage+' },
    { id: 41032, name: "Sérum Novage+ Wrinkle Smooth", brand: "Novage+", price: 52.00, imageUrl: getImg(41032), description: "Reduce arrugas profundas.", stock: 25, category: 'skincare', subCategory: 'Novage+' },
    { id: 41033, name: "Crema de Día Novage+ Bright Intense SPF 30", brand: "Novage+", price: 44.00, imageUrl: getImg(41033), description: "Luminosidad y protección avanzada.", stock: 35, category: 'skincare', subCategory: 'Novage+' },
    { id: 41034, name: "Crema de Día Novage+ Multi-Active SPF 30", brand: "Novage+", price: 44.00, imageUrl: getImg(41034), description: "Escudo protector diario.", stock: 40, category: 'skincare', subCategory: 'Novage+' },
    { id: 41037, name: "Crema de Noche Novage+ Multi-Active Rich", brand: "Novage+", price: 44.00, imageUrl: getImg(41037), description: "Reparación intensiva nocturna.", stock: 40, category: 'skincare', subCategory: 'Novage+' },
    { id: 41038, name: "Crema de Noche Novage+ Multi-Active Light", brand: "Novage+", price: 44.00, imageUrl: getImg(41038), description: "Textura ligera reparadora.", stock: 40, category: 'skincare', subCategory: 'Novage+' },
    { id: 41043, name: "Mascarilla de Noche Novage+ Intense Recharge", brand: "Novage+", price: 34.00, imageUrl: getImg(41043), description: "Recarga tu piel mientras duermes.", stock: 40, category: 'skincare', subCategory: 'Novage+' },
    { id: 41044, name: "Peeling Renovador Novage+", brand: "Novage+", price: 32.00, imageUrl: getImg(41044), description: "Exfoliación bionutritiva.", stock: 30, category: 'skincare', subCategory: 'Novage+' },
    { id: 42586, name: "Sérum Urban Guard Optimals", brand: "Optimals", price: 16.00, imageUrl: getImg(42586), description: "Protección contra la polución.", stock: 60, category: 'skincare', subCategory: 'Optimals', tag: 'OFERTA' },
    { id: 42587, name: "Limpiador 3 en 1 Urban Guard Optimals", brand: "Optimals", price: 12.00, imageUrl: getImg(42587), description: "Limpia, exfolia y purifica.", stock: 65, category: 'skincare', subCategory: 'Optimals' },
    { id: 42588, name: "Bruma Facial Urban Guard Optimals", brand: "Optimals", price: 10.00, imageUrl: getImg(42588), description: "Hidratación instantánea.", stock: 70, category: 'skincare', subCategory: 'Optimals' },
    { id: 42589, name: "Crema de Día Urban Guard SPF 20", brand: "Optimals", price: 14.00, imageUrl: getImg(42589), description: "Defensa urbana diaria.", stock: 55, category: 'skincare', subCategory: 'Optimals' },
    { id: 35503, name: "Crema de Día Royal Velvet Reafirmante", brand: "Royal Velvet", price: 29.00, imageUrl: getImg(35503), description: "Poder del Iris Negro.", stock: 50, category: 'skincare', subCategory: 'Royal Velvet' },
    { id: 35504, name: "Crema de Noche Royal Velvet Reparadora", brand: "Royal Velvet", price: 29.00, imageUrl: getImg(35504), description: "Firmeza mientras descansas.", stock: 50, category: 'skincare', subCategory: 'Royal Velvet' },
    { id: 34878, name: "Tender Care Arándano Azul", brand: "Oriflame", price: 12.00, imageUrl: getImg(34878), description: "Protección natural icónica.", stock: 150, category: 'skincare', subCategory: 'Oriflame' },
    { id: 42580, name: "Tender Care Fresa", brand: "Oriflame", price: 12.00, imageUrl: getImg(42580), description: "Bálsamo multiusos delicioso.", stock: 100, category: 'skincare', subCategory: 'Oriflame' },
    { id: 1276, name: "Tender Care Clásica", brand: "Oriflame", price: 12.00, imageUrl: getImg(1276), description: "El milagro sueco original.", stock: 200, category: 'skincare', subCategory: 'Oriflame' },
    { id: 35770, name: "Limpiador en Aceite Novage", brand: "Novage", price: 24.00, imageUrl: getImg(35770), description: "Elimina maquillaje y grasa.", stock: 45, category: 'skincare', subCategory: 'Novage' },
    { id: 33984, name: "Gel de Ojos Hydra Radiance Optimals", brand: "Optimals", price: 12.00, imageUrl: getImg(33984), description: "Despierta tu mirada.", stock: 80, category: 'skincare', subCategory: 'Optimals' },
    { id: 35462, name: "Agua Micelar Calmante Optimals", brand: "Optimals", price: 11.00, imageUrl: getImg(35462), description: "Limpia y calma pieles sensibles.", stock: 90, category: 'skincare', subCategory: 'Optimals' },
    { id: 35914, name: "Exfoliante Facial Love Nature - Albaricoque", brand: "Love Nature", price: 9.00, imageUrl: getImg(35914), description: "Energía frutal para tu piel.", stock: 110, category: 'skincare', subCategory: 'Love Nature' },
    { id: 35910, name: "Mascarilla Facial Love Nature - Aloe Vera", brand: "Love Nature", price: 8.00, imageUrl: getImg(35910), description: "Hidratación refrescante.", stock: 110, category: 'skincare', subCategory: 'Love Nature' },
    { id: 34039, name: "Tónico Hydra Radiance Optimals", brand: "Optimals", price: 11.00, imageUrl: getImg(34039), description: "Equilibra y refresca.", stock: 85, category: 'skincare', subCategory: 'Optimals' },
    { id: 41041, name: "Sérum Novage+ Bright Intense", brand: "Novage+", price: 52.00, imageUrl: getImg(41041), description: "Combate manchas y falta de brillo.", stock: 25, category: 'skincare', subCategory: 'Novage+' },

    // --- FRAGANCIAS (PERFUME) - 25+ PRODUCTOS ---
    { id: 38550, name: "All or Nothing Parfum", brand: "Oriflame", price: 60.00, imageUrl: getImg(38550), description: "Lujo máximo y exclusividad.", stock: 20, category: 'perfume' },
    { id: 33955, name: "Possess The Secret Man EdP", brand: "Oriflame", price: 42.00, imageUrl: getImg(33955), description: "Fuerza y carisma nórdico.", stock: 30, category: 'perfume' },
    { id: 33957, name: "Eclat Style Parfum", brand: "Oriflame", price: 48.00, imageUrl: getImg(33957), description: "Elegancia parisina atemporal.", stock: 25, category: 'perfume' },
    { id: 31293, name: "Eclat Femme EdT", brand: "Oriflame", price: 34.00, imageUrl: getImg(31293), description: "Sofisticación floral.", stock: 40, category: 'perfume' },
    { id: 35532, name: "So Fever Together For Her EdP", brand: "Oriflame", price: 36.00, imageUrl: getImg(35532), description: "Pasión y calidez.", stock: 35, category: 'perfume' },
    { id: 35531, name: "So Fever Together For Him EdT", brand: "Oriflame", price: 36.00, imageUrl: getImg(35531), description: "Magnética y sensual.", stock: 35, category: 'perfume' },
    { id: 34488, name: "Born to Fly For Her EdT", brand: "Oriflame", price: 30.00, imageUrl: getImg(34488), description: "Aventura y libertad.", stock: 45, category: 'perfume' },
    { id: 38531, name: "Signature Generation for Him EdT", brand: "Oriflame", price: 40.00, imageUrl: getImg(38531), description: "Legado y modernidad.", stock: 30, category: 'perfume' },
    { id: 38540, name: "Signature Generation for Her EdT", brand: "Oriflame", price: 40.00, imageUrl: getImg(38540), description: "Floral amaderado sofisticado.", stock: 30, category: 'perfume' },
    { id: 42786, name: "Love Potion Sensual Ruby EdP", brand: "Oriflame", price: 38.00, imageUrl: getImg(42786), description: "Deseo y seducción intensa.", stock: 25, category: 'perfume' },
    { id: 32235, name: "Elvie EdT", brand: "Oriflame", price: 28.00, imageUrl: getImg(32235), description: "Pureza de los bosques suecos.", stock: 50, category: 'perfume' },
    { id: 31099, name: "Love Potion EdP", brand: "Oriflame", price: 38.00, imageUrl: getImg(31099), description: "Afrodisíaco de chocolate y jengibre.", stock: 40, category: 'perfume' },
    { id: 32504, name: "Giordani Gold White Original EdP", brand: "Oriflame", price: 42.00, imageUrl: getImg(32504), description: "Pura alegría de vivir.", stock: 30, category: 'perfume' },
    { id: 42502, name: "Giordani Gold Essenza Parfum", brand: "Oriflame", price: 54.00, imageUrl: getImg(42502), description: "Oro líquido embotellado.", stock: 15, category: 'perfume' },
    { id: 33964, name: "Live In Colour EdP", brand: "Oriflame", price: 32.00, imageUrl: getImg(33964), description: "Explosión floral frutal.", stock: 40, category: 'perfume' },
    { id: 33959, name: "Amber Elixir Crystal EdP", brand: "Oriflame", price: 36.00, imageUrl: getImg(33959), description: "Misterio marino profundo.", stock: 35, category: 'perfume' },
    { id: 11367, name: "Amber Elixir EdP", brand: "Oriflame", price: 36.00, imageUrl: getImg(11367), description: "Calidez ámbar oriental.", stock: 45, category: 'perfume' },
    { id: 33654, name: "Possess The Secret For Her EdP", brand: "Oriflame", price: 42.00, imageUrl: getImg(33654), description: "Inspirada en Idunn.", stock: 30, category: 'perfume' },
    { id: 32150, name: "Giordani Gold Original EdP", brand: "Oriflame", price: 42.00, imageUrl: getImg(32150), description: "Icono de elegancia floral.", stock: 40, category: 'perfume' },
    { id: 31630, name: "Happydisiac Woman EdT", brand: "Oriflame", price: 26.00, imageUrl: getImg(31630), description: "Felicidad en cada spray.", stock: 55, category: 'perfume' },
    { id: 33413, name: "The Babes Crazy Kiwi EdT", brand: "Oriflame", price: 20.00, imageUrl: getImg(33413), description: "Divertida y juvenil.", stock: 60, category: 'perfume' },
    { id: 33958, name: "Love Potion So Tempting EdT", brand: "Oriflame", price: 24.00, imageUrl: getImg(33958), description: "Tentación dulce.", stock: 70, category: 'perfume' },
    { id: 42828, name: "Nordic Waters for Her EdP", brand: "Oriflame", price: 38.00, imageUrl: getImg(42828), description: "Frescura acuática pura.", stock: 40, category: 'perfume' },
    { id: 42811, name: "Nordic Waters for Him EdP", brand: "Oriflame", price: 38.00, imageUrl: getImg(42811), description: "Océano sueco embotellado.", stock: 40, category: 'perfume' },
    { id: 38521, name: "Venture Power EdT", brand: "Oriflame", price: 26.00, imageUrl: getImg(38521), description: "Energía urbana imparable.", stock: 50, category: 'perfume' },
    { id: 42519, name: "Eclat Mon Parfum", brand: "Oriflame", price: 54.00, imageUrl: getImg(42519), description: "Alta perfumería francesa.", stock: 20, category: 'perfume' },

    // --- OTROS PRODUCTOS (HAIR & PERSONAL CARE) ---
    { id: 31614, name: "Exfoliante Milk & Honey Gold", brand: "Milk & Honey Gold", price: 14.00, regularPrice: 18.00, imageUrl: getImg(31614), description: "Suavidad orgánica legendaria.", stock: 100, category: 'personal-care', subCategory: 'Milk & Honey Gold', tag: 'OFERTA' },
    { id: 31602, name: "Crema de Cuerpo Milk & Honey Gold", brand: "Milk & Honey Gold", price: 12.00, regularPrice: 16.00, imageUrl: getImg(31602), description: "Nutrición profunda con leche y miel.", stock: 150, category: 'personal-care', subCategory: 'Milk & Honey Gold', tag: 'OFERTA' },
    { id: 34912, name: "Champú en Seco HairX Advanced Care", brand: "Oriflame", price: 11.00, regularPrice: 14.00, imageUrl: getImg(34912), description: "Volumen y frescura sin agua.", stock: 90, category: 'hair', subCategory: 'Oriflame', tag: 'OFERTA' },
    { id: 38527, name: "Aceite de Noche Eleo Reparador", brand: "Oriflame", price: 18.00, regularPrice: 24.00, imageUrl: getImg(38527), description: "Tratamiento capilar de seda.", stock: 40, category: 'hair', subCategory: 'Oriflame', tag: 'OFERTA' },
];
