
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- COLECCIÓN MILK & HONEY GOLD ---
    {
        id: 47697,
        name: "Champú Nutritivo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 5.38,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47697%2F47697_1.png&MediaId=20669746&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Limpia delicadamente el cabello dejándolo suave, brillante y nutrido con extractos orgánicos.",
        stock: 200,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.0,
        reviewCount: 1,
    },
    {
        id: 47698,
        name: "Acondicionador Nutritivo Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 5.38,
        regularPrice: 12.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47698%2F47698_1.png&MediaId=20669754&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Desenreda y nutre intensamente el cabello. Fórmula cremosa con aroma icónico.",
        stock: 150,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 0,
        reviewCount: 0,
    },
    {
        id: 47537,
        name: "Jabón Líquido para Manos y Cuerpo Majestic Magnolia",
        brand: "Milk & Honey Gold",
        price: 9.23,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47537%2F47537_1.png&MediaId=20483922&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Edición limitada con extracto de Magnolia que deja la piel fresca y delicadamente perfumada.",
        stock: 80,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 330,
    },
    {
        id: 47536,
        name: "Crema para Manos y Cuerpo Majestic Magnolia",
        brand: "Milk & Honey Gold",
        price: 9.23,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png&MediaId=20483897&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Textura rica y nutritiva para una hidratación 24h con el sofisticado aroma de la Magnolia.",
        stock: 120,
        category: 'personal-care',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 669,
    },
    {
        id: 31602,
        name: "Jabón Líquido de Manos Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 8.99,
        regularPrice: 13.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F31602%2F31602_1.png",
        description: "Lujoso jabón líquido con extractos de leche y miel de origen orgánico para una piel nutrida.",
        stock: 500,
        category: 'personal-care',
        tag: 'SET',
        rating: 4.9,
        reviewCount: 1250,
    },
    {
        id: 31606,
        name: "Crema Nutritiva de Manos y Cuerpo Milk & Honey",
        brand: "Milk & Honey Gold",
        price: 12.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F31606%2F31606_1.png",
        description: "Acondiciona la piel intensamente dejándola con un aroma icónico y suavidad dorada.",
        stock: 350,
        category: 'personal-care',
        rating: 5.0,
        reviewCount: 4200,
    },
    {
        id: 46970,
        name: "Crema de Ducha Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 11.55,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46970%2F46970_1.png&MediaId=19554596&Version=1&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Limpia y suaviza la piel con una espuma rica y cremosa infundida con extractos orgánicos.",
        stock: 300,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1369,
    },
    {
        id: 46969,
        name: "Exfoliante Corporal de Azúcar Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 13.09,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46969%2F46969_1.png&MediaId=19554576&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Elimina las células muertas dejando la piel increíblemente suave y pulida.",
        stock: 250,
        category: 'personal-care',
        rating: 4.9,
        reviewCount: 1218,
    },

    // --- COLECCIÓN FESTIVE & GIFTING ---
    {
        id: 48977,
        name: "Sobre de Regalo Festive",
        brand: "Vella Festive",
        price: 1.53,
        regularPrice: 2.99,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48977%2F48977_1.png",
        description: "Sobre elegante para pequeños detalles de joyería o maquillaje.",
        stock: 50,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 4.9,
        reviewCount: 34,
    },
    {
        id: 48975,
        name: "Bolsa-Sobre de Regalo Festive",
        brand: "Vella Festive",
        price: 2.69,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48975%2F48975_1.png",
        description: "Bolsa tipo sobre versátil con cierre magnético ideal para sets.",
        stock: 120,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 4.8,
        reviewCount: 170,
    },
    {
        id: 48565,
        name: "Jabonera Magnolia",
        brand: "Milk & Honey Gold",
        price: 11.54,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48565%2F48565_1.png&MediaId=20483934&Version=2&w=600&bc=%23f5f5f5&ib=%23f5f5f5&h=600&q=90&imageFormat=WebP",
        description: "Accesorio decorativo y funcional para conservar tus jabones sólidos con estilo.",
        stock: 45,
        category: 'accessories',
        tag: 'NOVEDAD',
        rating: 5.0,
        reviewCount: 113,
    },

    // --- COSMÉTICOS Y PERFUMERÍA ---
    {
        id: 34545,
        name: "Perlas Bronceadoras Giordani Gold",
        brand: "Giordani Gold",
        price: 21.99,
        regularPrice: 34.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34545%2F34545_1.png",
        description: "Perlas bronceadoras icónicas enriquecidas con ácido hialurónico.",
        stock: 50,
        category: 'makeup',
        tag: 'OFERTA',
        rating: 4.9,
        reviewCount: 1542,
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 27.99,
        regularPrice: 45.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia Chipre Floral Amaderada que deja una estela hipnótica.",
        stock: 30,
        category: 'perfume',
        tag: 'NOVEDAD',
        rating: 5,
        reviewCount: 26,
    },
    {
        id: 38497,
        name: "Eau de Parfum Divine",
        brand: "Divine",
        price: 24.99,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "Celebra tu feminidad con el icónico aroma de Divine, una fragancia floral fresca y sofisticada.",
        stock: 200,
        category: 'perfume',
        rating: 4.9,
        reviewCount: 3100
    }
];
