
import type { Product } from './types';

export const allProducts: Product[] = [
    // --- COLECCIÓN COFRES ESSENZA NAVIDAD 2026 ---
    {
        id: 42502,
        name: "Cofre Joya Essenza Blossom Rojo (Perfume + Crema)",
        brand: "Giordani Gold",
        price: 49.99,
        regularPrice: 95.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42502%2F42502_1.png",
        description: "EDICIÓN LIMITADA NAVIDAD 2026. El cofre de lujo de Essenza. Incluye el perfume Essenza Blossom en su icónico frasco rojo joya de 50ml y la Crema Corporal Perfumada hidratante. Notas de Jazmín y Camelia Blossom.",
        stock: 50,
        category: 'perfume',
        subCategory: 'Giordani Gold',
        productType: 'Cofre',
        tag: 'SET',
        beautyPoints: 120
    },
    {
        id: 42503,
        name: "Set Essenza Gold Luxury Edition",
        brand: "Giordani Gold",
        price: 55.00,
        regularPrice: 105.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F42502%2F42502_1.png",
        description: "El lujo original de Essenza. Set con Parfum Essenza 50ml y Desodorante en Spray perfumado. El aroma del oro líquido.",
        stock: 35,
        category: 'perfume',
        subCategory: 'Giordani Gold',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- COFRES CLAT (ECLAT) ---
    {
        id: 45001,
        name: "Cofre Clat Style Hombre (Eclat Set)",
        brand: "Oriflame",
        price: 39.99,
        regularPrice: 75.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F34522%2F34522_1.png",
        description: "Elegancia parisina en set. Incluye Eclat Style Parfum 75ml y Desodorante perfumado de alta protección. El regalo ideal para él.",
        stock: 40,
        category: 'perfume',
        subCategory: 'Oriflame',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- COFRES POSSESS ---
    {
        id: 45002,
        name: "Cofre Dúo Possess The Secret (Perfume + Roll-on)",
        brand: "Oriflame",
        price: 34.99,
        regularPrice: 68.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F33955%2F33955_1.png",
        description: "Fuerza nórdica para regalar. Set con Eau de Parfum 50ml y Desodorante Roll-on perfumado. Aroma de Manzana Golden e Idunn.",
        stock: 45,
        category: 'perfume',
        subCategory: 'Oriflame',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- COFRES ELVI (ELVIE) ---
    {
        id: 45007,
        name: "Cofre Elvi Magic (Elvie Set + Loción)",
        brand: "Oriflame",
        price: 24.99,
        regularPrice: 48.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F32235%2F32235_1.png",
        description: "La magia de los bosques suecos. Set incluye Elvie Eau de Toilette 50ml y Loción Corporal hidratante perfumada. Aroma fresco y floral.",
        stock: 60,
        category: 'perfume',
        subCategory: 'Oriflame',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- COFRES NORDIC WATERS ---
    {
        id: 45008,
        name: "Set Nordic Waters Ocean Breeze",
        brand: "Oriflame",
        price: 29.99,
        regularPrice: 55.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F43122%2F43122_1.png",
        description: "Siente el frescor del océano. Set de fragancia 50ml y desodorante refrescante. Pureza nórdica en cada gota.",
        stock: 50,
        category: 'perfume',
        subCategory: 'Oriflame',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- COFRES DIVINE IDOLO ---
    {
        id: 45009,
        name: "Cofre Divine Idolo Exclusive (Parfum + Roll-on)",
        brand: "Oriflame",
        price: 42.00,
        regularPrice: 80.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F38497%2FES%2F38497_1.png",
        description: "Para la mujer que nació para ser ídolo. Set premium con Divine Exclusive Parfum y su Roll-on perfumado a juego.",
        stock: 20,
        category: 'perfume',
        subCategory: 'Oriflame',
        productType: 'Cofre',
        tag: 'SET'
    },

    // --- MAQUILLAJE ---
    {
        id: 40657,
        name: "Labial Iconic SPF 15 Giordani Gold",
        brand: "Giordani Gold",
        price: 10.99,
        regularPrice: 22.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40657%2F40657_1.png",
        description: "Color intenso y cremoso con Aceite de Argán. Protección solar y lujo absoluto de Giordani.",
        stock: 150,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        productType: 'Labial',
        tag: 'OFERTA',
        variants: {
            "Tono": [
                { value: "Heritage Red", colorCode: "#a31d25" },
                { value: "Royal Pink", colorCode: "#e34d67" },
                { value: "Classic Nude", colorCode: "#c48a73" }
            ]
        }
    },
    {
        id: 40770,
        name: "Perlas Bronceadoras Gould MasterCreation",
        brand: "Giordani Gold",
        price: 16.99,
        regularPrice: 34.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F40770%2F44521_1.png",
        description: "Perlas hechas a mano en Italia con Esencia de Juventud para un brillo sofisticado.",
        stock: 200,
        category: 'makeup',
        subCategory: 'Giordani Gold',
        productType: 'Colorete y Bronceador',
        tag: 'OFERTA'
    },

    // --- PRODUCTOS RECIENTES ---
    {
        id: 48028,
        name: "Eau de Parfum Giordani Gold White",
        brand: "Giordani Gold",
        price: 22.32,
        regularPrice: 49.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48028%2F48028_1.png",
        description: "Una fragancia luminosa y sofisticada que captura la esencia de la elegancia pura. Notas de flores blancas y almizcle.",
        stock: 45,
        category: 'perfume',
        subCategory: 'Giordani Gold',
        productType: 'Cofre',
        tag: 'NOVEDAD'
    },
    {
        id: 48105,
        name: "Mascarilla Revitalizante Intensiva Acción Noche Novage+ - Edición Especial",
        brand: "Novage+",
        price: 20.78,
        regularPrice: 39.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48105%2F48105_1.png",
        description: "Tratamiento nocturno ultra-nutritivo que restaura la luminosidad y firmeza de la piel mientras duermes.",
        stock: 100,
        category: 'skincare',
        subCategory: 'Novage+',
        productType: 'Mascarilla',
        tag: 'NOVEDAD'
    },
    {
        id: 47188,
        name: "Iluminador Líquido Illuskin THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47188%2F47188_1.png",
        description: "Iluminador líquido de alta definición para un brillo natural y radiante. Textura ligera y fácil de difuminar.",
        stock: 80,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Iluminador',
        tag: 'NOVEDAD'
    },
    {
        id: 46319,
        name: "Niacinamida 10% Power Drops Proceuticals Novage+",
        brand: "Novage+",
        price: 43.89,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46319%2F46319_1.png",
        description: "Sérum concentrado con 10% de Niacinamida para minimizar poros y mejorar la textura de la piel.",
        stock: 60,
        category: 'skincare',
        subCategory: 'Novage+',
        productType: 'Sérum',
        tag: 'NOVEDAD'
    },
    {
        id: 46801,
        name: "Eau de Parfum Divine Dark Velvet",
        brand: "Divine",
        price: 34.65,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F46801%2F46801_1.png",
        description: "Una fragancia cautivadora y sensual con notas de terciopelo y maderas nobles.",
        stock: 30,
        category: 'perfume',
        subCategory: 'Divine',
        productType: 'Cofre',
        tag: 'NOVEDAD'
    },
    {
        id: 47977,
        name: "Brillo para Pestañas y Cejas Glitter THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47977%2F47977_1.png",
        description: "Añade un toque de brillo a tu mirada con este gel con purpurina fina para cejas y pestañas.",
        stock: 120,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Máscara',
        tag: 'NOVEDAD'
    },
    {
        id: 48115,
        name: "Crema de Día Reafirmante SPF 20 Royal Velvet - Edición Especial",
        brand: "Royal Velvet",
        price: 19.24,
        regularPrice: 42.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48115%2F48115_1.png",
        description: "Fórmula clásica reafirmante enriquecida con Flor de Iris para una piel más elástica y protegida.",
        stock: 55,
        category: 'skincare',
        subCategory: 'Royal Velvet',
        productType: 'Crema Noche',
        tag: 'NOVEDAD'
    },
    {
        id: 48650,
        name: "Máscara de Pestañas Winter Wonder Lash Waterproof THE ONE",
        brand: "The ONE",
        price: 5.77,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48650%2F48650_1.png",
        description: "Volumen y longitud extremos en una fórmula resistente al agua de larga duración.",
        stock: 200,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Máscara',
        tag: 'NOVEDAD'
    },
    {
        id: 47537,
        name: "Jabón Líquido para Manos y Cuerpo Majestic Magnolia Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 9.23,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47537%2F47537_1.png",
        description: "Limpieza cremosa con extractos de leche y miel orgánica y aroma a magnolia.",
        stock: 90,
        category: 'personal-care',
        subCategory: 'Milk & Honey Gold',
        productType: 'Higiene',
        tag: 'NOVEDAD'
    },
    {
        id: 47538,
        name: "Jabón en Barra Majestic Magnolia Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 3.07,
        regularPrice: 6.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47538%2F47538_1.png",
        description: "Barra de jabón nutritiva que deja la piel suave y delicadamente perfumada.",
        stock: 150,
        category: 'personal-care',
        subCategory: 'Milk & Honey Gold',
        productType: 'Higiene',
        tag: 'NOVEDAD'
    },
    {
        id: 47536,
        name: "Crema para Manos y Cuerpo Majestic Magnolia Milk & Honey Gold",
        brand: "Milk & Honey Gold",
        price: 9.23,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47536%2F47536_1.png",
        description: "Hidratación profunda 24h con un acabado sedoso y aroma floral irresistible.",
        stock: 85,
        category: 'personal-care',
        subCategory: 'Milk & Honey Gold',
        productType: 'Higiene',
        tag: 'NOVEDAD'
    },
    {
        id: 48085,
        name: "Lote Be the Legend",
        brand: "Be the Legend",
        price: 17.70,
        regularPrice: 58.50,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48085%2F48085_1.png",
        description: "Set completo para el hombre seguro de sí mismo. Incluye fragancia y productos de higiene.",
        stock: 25,
        category: 'perfume',
        subCategory: 'Be the Legend',
        productType: 'Lote',
        tag: 'NOVEDAD'
    },
    {
        id: 48039,
        name: "Máscara de Pestañas Hypnotic Colour THE ONE",
        brand: "The ONE",
        price: 6.92,
        regularPrice: 18.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48039%2F48039_1.png",
        description: "Colores vibrantes para tus pestañas con un efecto hipnótico y definidor.",
        stock: 75,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Máscara',
        tag: 'NOVEDAD'
    },
    {
        id: 47192,
        name: "Sombra de Ojos Líquida THE ONE",
        brand: "The ONE",
        price: 7.69,
        regularPrice: 20.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47192%2F47192_1.png",
        description: "Sombra líquida de secado rápido con pigmentos intensos y acabado metalizado.",
        stock: 95,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Sombra',
        tag: 'NOVEDAD'
    },
    {
        id: 48675,
        name: "Caja de Regalo Crema Universal - Grosella Negra, Original Edición Especial y Ciruela Dulce",
        brand: "Crema Universal",
        price: 27.72,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48675%2F48675_1.png",
        description: "El regalo perfecto: trío de bálsamos icónicos en una caja de lujo.",
        stock: 40,
        category: 'skincare',
        subCategory: 'Crema Universal',
        productType: 'Caja Regalo',
        tag: 'NOVEDAD'
    },
    {
        id: 48083,
        name: "Lote Love Potion Cherry on Top",
        brand: "Love Potion",
        price: 45.82,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48083%2F48083_1.png",
        description: "Un set seductor con el dulce aroma de la cereza y la vainilla.",
        stock: 20,
        category: 'perfume',
        subCategory: 'Love Potion',
        productType: 'Lote',
        tag: 'NOVEDAD'
    },
    {
        id: 47271,
        name: "Gel Aftershave North For Men by Giordani Gold",
        brand: "North for Men",
        price: 11.55,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47271%2F47271_1.png",
        description: "Calma y protege la piel después del afeitado con un toque de lujo italiano.",
        stock: 65,
        category: 'men',
        subCategory: 'North for Men',
        productType: 'Higiene',
        tag: 'NOVEDAD'
    },
    {
        id: 47270,
        name: "Espuma de Limpieza y Afeitado 2 en 1 North For Men by Giordani Gold",
        brand: "North for Men",
        price: 13.48,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F47270%2F47270_1.png",
        description: "Fórmula versátil para una limpieza profunda y un afeitado suave sin irritaciones.",
        stock: 50,
        category: 'men',
        subCategory: 'North for Men',
        productType: 'Limpiador',
        tag: 'NOVEDAD'
    },
    {
        id: 48640,
        name: "Barra de Labios Líquida Glitter THE ONE",
        brand: "The ONE",
        price: 6.54,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48640%2F48640_1.png",
        description: "Labial líquido con acabado glitter de alto impacto y larga duración.",
        stock: 110,
        category: 'makeup',
        subCategory: 'THE ONE',
        productType: 'Labial',
        tag: 'NOVEDAD'
    },
    {
        id: 48082,
        name: "Lote GG Essenza Supreme",
        brand: "Giordani Gold",
        price: 66.61,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48082%2F48082_1.png",
        description: "La máxima expresión del lujo Giordani Gold en un set exclusivo.",
        stock: 15,
        category: 'perfume',
        subCategory: 'Giordani Gold',
        productType: 'Lote',
        tag: 'NOVEDAD'
    },
    {
        id: 48084,
        name: "Lote Amber Elixir",
        brand: "Amber Elixir",
        price: 50.44,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48084%2F48084_1.png",
        description: "El aroma cálido del ámbar en un lote diseñado para regalar.",
        stock: 18,
        category: 'perfume',
        subCategory: 'Amber Elixir',
        productType: 'Lote',
        tag: 'NOVEDAD'
    },
    {
        id: 48918,
        name: "Masajeador Cryo Facial Arctic Ritual",
        brand: "Oriflame",
        price: 6.92,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48918%2F48918_1.png",
        description: "Herramienta de masaje facial con efecto frío para descongestionar y reafirmar.",
        stock: 100,
        category: 'accessories',
        subCategory: 'Arctic Ritual',
        productType: 'Accesorio',
        tag: 'NOVEDAD'
    },
    {
        id: 48915,
        name: "Turbante de Satén Arctic Ritual",
        brand: "Oriflame",
        price: 6.92,
        regularPrice: 15.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48915%2F48915_1.png",
        description: "Turbante de satén suave para proteger el cabello y mantener tu rutina facial impecable.",
        stock: 80,
        category: 'accessories',
        subCategory: 'Arctic Ritual',
        productType: 'Accesorio',
        tag: 'NOVEDAD'
    },
    {
        id: 48649,
        name: "Crema Universal Original - Edición Especial",
        brand: "Crema Universal",
        price: 10.78,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48649%2F48649_1.png",
        description: "El bálsamo multiusos clásico en un envase de colección especial.",
        stock: 300,
        category: 'skincare',
        subCategory: 'Crema Universal',
        productType: 'Bálsamo',
        tag: 'NOVEDAD'
    },
    {
        id: 48570,
        name: "Reloj Magical Midnights",
        brand: "Oriflame",
        price: 23.09,
        regularPrice: 44.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48570%2F48570_1.png",
        description: "Elegante reloj de pulsera con detalles inspirados en la noche estrellada.",
        stock: 40,
        category: 'accessories',
        subCategory: 'Magical Midnights',
        productType: 'Reloj',
        tag: 'NOVEDAD'
    },
    {
        id: 48568,
        name: "Pendientes Magical Midnights",
        brand: "Oriflame",
        price: 6.54,
        regularPrice: 17.00,
        imageUrl: "https://media-cdn.oriflame.com/productImage?externalMediaId=product-management-media%2FProducts%2F48568%2F48568_1.png",
        description: "Pendientes delicados con cristales brillantes para tus noches especiales.",
        stock: 60,
        category: 'accessories',
        subCategory: 'Magical Midnights',
        productType: 'Pendientes',
        tag: 'NOVEDAD'
    },
    {
        id: 48569,
        name: "Collar Magical Midnights",
        brand: "Oriflame",
        price: 11.54